resources:

# Inventory:
- v1alpha1_inventory.yaml

# Hardware management:
- v1alpha1_node.yaml
- v1alpha1_nodepool.yaml
- v1alpha1_hardwaretemplate.yaml

# Provisioning:
- v1alpha1_clustertemplate.yaml
- v1alpha1_provisioningrequest.yaml

