apiVersion: v1
kind: ConfigMap
metadata:
  name: clustertemplate-sample.v1.0.0-policytemplate-defaults
  namespace: clustertemplate-a-v4-16
data:
  clusterConfigurationTimeout: "40" # optional
  policytemplate-defaults: |
    sriov-network-pfNames-1: "eno2"
    sriov-network-pfNames-2: "eno3"
    cpu-isolated: "2-23,26-47"
    cpu-reserved: "0-1,24-25"
    hugepages-default: "1G"
    hugepages-size: "1G"
    hugepages-count: "32"
    install-plan-approval: "Automatic"
